version: '3.2'

services:
  server:
    build: .
    image: miner-proxy:latest
    ports:
      - 9998:9999
    command: miner-proxy -l :9999 -r eth-sg.flexpool.io:4444 -k 12345

  client:
    build: .
    image: miner-proxy:latest
    ports:
      - 9999:9999
    command: miner-proxy -l :9999 -r server:9999 -k 12345 -c
